### ISSUE TITLE
Redesign Main Menu & Info page

### ISSUE THREAD

**Issue by kimmix93** [codingNonGuru/MayorDanger#16]

**Comment by kimmix93** [comment]
![healthbar_happy](https://user-images.githubusercontent.com/44111916/47723522-58854b80-dc5d-11e8-8b2c-8b822f4bd14a.png)
![healthbar_sad](https://user-images.githubusercontent.com/44111916/47723524-58854b80-dc5d-11e8-80d8-55460c26fcff.png)
![stampila](https://user-images.githubusercontent.com/44111916/47723526-591de200-dc5d-11e8-9d8b-25a4ddfaa015.png)


o propunere pentru cand e timp ar fi sa isi schimbe expresia in functie de cate voturi mai are

**Comment by kimmix93** [comment]
![info page](https://user-images.githubusercontent.com/44111916/47746659-25f44680-dc8f-11e8-8927-75257cb0c2a9.png)
![inapoi](https://user-images.githubusercontent.com/44111916/47746660-268cdd00-dc8f-11e8-8644-91cfddd51d4d.png)

**Comment by kimmix93** [comment]
![main menu](https://user-images.githubusercontent.com/44111916/47749404-c2b9e280-dc95-11e8-8afb-8d47de1b37ec.png)

**Comment by codingNonGuru** [comment]
Arata foarte OK. Sunt un upgrade clar fata de ce avem.

**Comment by kimmix93** [comment]
Cred ca varianta din mijloc e cea mai clean. Atasez aici png-urile cu transparenta.
@FlaviaDbr @codingNonGuru 


![pagina main menu](https://user-images.githubusercontent.com/44111916/47805784-d66e5300-dd40-11e8-9d53-90c72d995bba.png)
![info_buton](https://user-images.githubusercontent.com/44111916/47805817-e9812300-dd40-11e8-881d-18171bb678ef.png)
![play_buton](https://user-images.githubusercontent.com/44111916/47805818-ea19b980-dd40-11e8-9b6c-e47257fa1377.png)
![titlu](https://user-images.githubusercontent.com/44111916/47805789-d8d0ad00-dd40-11e8-961f-9dfef38eab64.png)

**Comment by kimmix93** [comment]
@codingNonGuru 
![taste](https://user-images.githubusercontent.com/44111916/47953013-1a9b6680-df80-11e8-8d41-8b5ec4c23e6a.png)
![mouse](https://user-images.githubusercontent.com/44111916/47953014-1a9b6680-df80-11e8-8b18-acb99c34387e.png)
![taste descriere](https://user-images.githubusercontent.com/44111916/47953015-1b33fd00-df80-11e8-9e27-c6e927c64a78.png)
![mouse descriere](https://user-images.githubusercontent.com/44111916/47953016-1b33fd00-df80-11e8-9db1-d17bef2b465c.png)
