### ISSUE TITLE
(misc) Wider Background

### ISSUE THREAD

**Issue by kimmix93** [codingNonGuru/MayorDanger#19]

**Comment by kimmix93** [comment]
@codingNonGuru 
as vrea sa stiu ca e batuta in cuie treaba cu 16:9, nu mi-as dori sa lucrez degeaba la el.

**Comment by codingNonGuru** [comment]
Am zis ca facem 16:9 daca facem ChickInv. Asteapta, te rog, sa vedem daca ramane ChickInv. Daca ramane, atunci clar facem 16:9.

**Comment by kimmix93** [comment]
@codingNonGuru 

![bg_extra large](https://user-images.githubusercontent.com/44111916/47953045-81208480-df80-11e8-8da9-df7f47ea6f1a.png)
