### ISSUE TITLE
Refine 'Game Over' messages

### ISSUE THREAD

**Issue by codingNonGuru** [codingNonGuru/MayorDanger#5]

**Comment by kimmix93** [comment]
@FlaviaDbr @codingNonGuru & everyone 

Am cautat un font mai potrivit. Mi-a dat un vibe de "tovaras", amestecat cu "eticheta de palinca"
Let me know what you think 

![win_03](https://user-images.githubusercontent.com/44111916/47729587-1e21ab80-dc69-11e8-836a-cbf984f07937.png)

**Comment by kimmix93** [comment]
*cont*

![lose_03](https://user-images.githubusercontent.com/44111916/47731404-b66d5f80-dc6c-11e8-9fb2-b8ff691bbd07.png)

**Comment by kimmix93** [comment]
![restart](https://user-images.githubusercontent.com/44111916/47732232-74451d80-dc6e-11e8-8e50-dcca5f04cbe4.png)
![win_bubble](https://user-images.githubusercontent.com/44111916/47732233-74451d80-dc6e-11e8-840a-fb96c225421e.png)
![end button card](https://user-images.githubusercontent.com/44111916/47732234-74451d80-dc6e-11e8-82cb-0c72c258bcb5.png)
![lose_bubble](https://user-images.githubusercontent.com/44111916/47732235-74ddb400-dc6e-11e8-8e7b-75e9e770ce58.png)
![main menu](https://user-images.githubusercontent.com/44111916/47732237-74ddb400-dc6e-11e8-8cbf-651d12841561.png)

**Comment by kimmix93** [comment]
![restart](https://user-images.githubusercontent.com/44111916/47741811-e7a55a00-dc83-11e8-8ace-921251f4f029.png)

**Comment by StickSilviu** [comment]
E fain rau scrisul acesta :+1:
