### ISSUE TITLE
Replace 'Next' button w/ custom-made dialog bubbles

### ISSUE THREAD

**Issue by codingNonGuru** [codingNonGuru/MayorDanger#8]

**Comment by kimmix93** [comment]
Preview:

![bubbles dialog_v04](https://user-images.githubusercontent.com/44111916/47724805-0f82c680-dc60-11e8-8f0f-afc0dc4d7305.png)
![bubbles dialog2_v04](https://user-images.githubusercontent.com/44111916/47724807-0f82c680-dc60-11e8-9fcc-24faf1ef7de0.png)

**Comment by kimmix93** [comment]
Asset-uri: 
![dialog1](https://user-images.githubusercontent.com/44111916/47725461-49a09800-dc61-11e8-8489-c7bacca43980.png)
![dialog2](https://user-images.githubusercontent.com/44111916/47725462-49a09800-dc61-11e8-9cb8-90a786c6141c.png)
![continua](https://user-images.githubusercontent.com/44111916/47725465-49a09800-dc61-11e8-89b4-58b6d6684318.png)

**Comment by kimmix93** [comment]
Also, sa stabilim daca textul ramane asa sau daca il schimbam. 
@FlaviaDbr

**Comment by kimmix93** [comment]
![blank button](https://user-images.githubusercontent.com/44111916/47745989-ac0f8d80-dc8d-11e8-9066-29f38babe87e.png)

**Comment by codingNonGuru** [comment]
@kimmix93 Da-mi separat si cele 2 bule de dialog, te rog.
