### ISSUE TITLE
Improve visual aspect for Health Bar

### ISSUE THREAD

**Issue by codingNonGuru** [codingNonGuru/MayorDanger#9]

**Comment by kimmix93** [comment]
![healthbar_happy](https://user-images.githubusercontent.com/44111916/47723766-e6f9cd00-dc5d-11e8-96cf-9ba4cd04a9d2.png)
![healthbar_sad](https://user-images.githubusercontent.com/44111916/47723768-e6f9cd00-dc5d-11e8-93f2-d2ad7eba2fac.png)
![stampila](https://user-images.githubusercontent.com/44111916/47723769-e7926380-dc5d-11e8-88a2-7bf04d29449f.png)

+cand e timp: propun sa isi schimbe expresia in functie de nr de voturi.

**Comment by codingNonGuru** [comment]
Arata bine. Cateva sugestii: 
(1) Hartiei cu Nego pune-i patru gauri, ca e mai inalta. 
(2) Scoate gaurile de sub hartia cu Nego, ca arata ambiguu.
(3) In loc de 'VOTAT' sa fie 'VOT' - se vede mai clar de la distanta.

In rest, imi place mult cum se contureaza.

**Comment by kimmix93** [comment]
![healthbar_happy_02](https://user-images.githubusercontent.com/44111916/47731172-3f37cb80-dc6c-11e8-9245-c329080c8c59.png)
![healthbar_sad_02](https://user-images.githubusercontent.com/44111916/47731173-3f37cb80-dc6c-11e8-81fe-54011c1debd3.png)
![stampila_02](https://user-images.githubusercontent.com/44111916/47731178-4068f880-dc6c-11e8-8794-54c48d267b5f.png)

**Comment by codingNonGuru** [comment]
Geniala ideea cu schimbatul expresiei. Dau imediat deploy la noul build.
